AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPCPeeringConnectionCIandDev:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !ImportValue 
        'Fn::Sub': ci-vpc-VPCID
      PeerVpcId: !ImportValue 
        'Fn::Sub': dev-vpc-VPCID
      Tags:
        - Key: Name
          Value: PeeringCIAndDev
  VPCPeeringConnectionCIandProd:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !ImportValue 
        'Fn::Sub': ci-vpc-VPCID
      PeerVpcId: !ImportValue 
        'Fn::Sub': prod-vpc-VPCID
      Tags:
        - Key: Name
          Value: PeeringCIAndProd
  PeeringRouteCItoDevPublic:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref DevVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': ci-vpc-PublicNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandDev
  PeeringRouteDevtoCIPublic:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref CIVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': dev-vpc-PublicNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandDev
  PeeringRouteCItoDevPrivate:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref DevVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': ci-vpc-PrivateNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandDev
  PeeringRouteDevtoCIPrivate:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref CIVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': dev-vpc-PrivateNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandDev
  PeeringRouteCItoProdPublic:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref ProdVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': ci-vpc-PublicNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandProd
  PeeringRouteProdtoCIPublic:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref CIVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': prod-vpc-PublicNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandProd
  PeeringRouteCItoProdPrivate:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref ProdVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': ci-vpc-PrivateNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandProd
  PeeringRouteProdtoCIPrivate:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref CIVPCIDCIDRRange
      RouteTableId: !ImportValue 
        'Fn::Sub': prod-vpc-PrivateNetRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCIandProd
Parameters:
  projectTag:
    Description: Project Name for Tagging Purposes
    Type: String
    Default: napote
  DevVPCIDCIDRRange:
    Description: Dev VPC CIDR
    Type: String
    Default: 10.44.0.0/16
  CIVPCIDCIDRRange:
    Description: CI VPC CIDR
    Type: String
    Default: 10.55.0.0/16
  ProdVPCIDCIDRRange:
    Description: Prod VPC CIDR
    Type: String
    Default: 10.66.0.0/16
Outputs:
  PseudoOutput:
    Description: PseudoOutput
    Value: PseudoOutput
Description: Configures peering between VPCs

