(ns ote.mui-wrapper.reagent
  (:refer-clojure :exclude [list stepper])
  (:require [reagent.core :as r]
            ["@material-ui/core" :as mui]
            [reagent.impl.template]
            [reagent.interop :refer-macros [$ $!]]))

(def app-bar nil #_(r/adapt-react-class (aget js/MaterialUI "AppBar")))
(def auto-complete nil #_(r/adapt-react-class (aget js/MaterialUI "AutoComplete")))
(def avatar nil #_(r/adapt-react-class (aget js/MaterialUI "Avatar")))
(def badge nil #_(r/adapt-react-class (aget js/MaterialUI "Badge")))
(def bottom-navigation nil #_(r/adapt-react-class (aget js/MaterialUI "BottomNavigation")))
(def bottom-navigation-item nil #_(r/adapt-react-class (aget js/MaterialUI "BottomNavigationItem")))
(def card nil #_(r/adapt-react-class (aget js/MaterialUI "Card")))
(def card-actions nil #_(r/adapt-react-class (aget js/MaterialUI "CardActions")))
(def card-header nil #_(r/adapt-react-class (aget js/MaterialUI "CardHeader")))
(def card-media nil #_(r/adapt-react-class (aget js/MaterialUI "CardMedia")))
(def card-title nil #_(r/adapt-react-class (aget js/MaterialUI "CardTitle")))
(def card-text nil #_(r/adapt-react-class (aget js/MaterialUI "CardText")))
(def checkbox nil #_(r/adapt-react-class (aget js/MaterialUI "Checkbox")))
(def chip nil #_(r/adapt-react-class (aget js/MaterialUI "Chip")))
(def circular-progress nil #_(r/adapt-react-class (aget js/MaterialUI "CircularProgress")))
(def date-picker nil #_(r/adapt-react-class (aget js/MaterialUI "DatePicker")))
(def dialog nil #_(r/adapt-react-class (aget js/MaterialUI "Dialog")))
(def divider nil #_(r/adapt-react-class (aget js/MaterialUI "Divider")))
(def drawer nil #_(r/adapt-react-class (aget js/MaterialUI "Drawer")))
(def drop-down-menu nil #_(r/adapt-react-class (aget js/MaterialUI "DropDownMenu")))
(def flat-button nil #_(r/adapt-react-class (aget js/MaterialUI "FlatButton")))
(def floating-action-button nil #_(r/adapt-react-class (aget js/MaterialUI "FloatingActionButton")))
(def font-icon nil #_(r/adapt-react-class (aget js/MaterialUI "FontIcon")))
(def grid-list nil #_(r/adapt-react-class (aget js/MaterialUI "GridList")))
(def grid-tile nil #_(r/adapt-react-class (aget js/MaterialUI "GridTile")))
(def icon-button nil #_(r/adapt-react-class (aget js/MaterialUI "IconButton")))
(def icon-menu nil #_(r/adapt-react-class (aget js/MaterialUI "IconMenu")))
(def linear-progress nil #_(r/adapt-react-class (aget js/MaterialUI "LinearProgress")))
(def list nil #_(r/adapt-react-class (aget js/MaterialUI "List")))
(def list-item nil #_(r/adapt-react-class (aget js/MaterialUI "ListItem")))
(def menu nil #_(r/adapt-react-class (aget js/MaterialUI "Menu")))
(def menu-item nil #_(r/adapt-react-class (aget js/MaterialUI "MenuItem")))
(def mui-theme-provider nil #_(r/adapt-react-class (aget js/MaterialUI "MuiThemeProvider")))
(def paper nil #_(r/adapt-react-class (aget js/MaterialUI "Paper")))
(def popover nil #_(r/adapt-react-class (aget js/MaterialUI "Popover")))
(def radio-button nil #_(r/adapt-react-class (aget js/MaterialUI "RadioButton")))
(def radio-button-group nil #_(r/adapt-react-class (aget js/MaterialUI "RadioButtonGroup")))
(def raised-button nil #_(r/adapt-react-class (aget js/MaterialUI "RaisedButton")))
(def refresh-indicator nil #_(r/adapt-react-class (aget js/MaterialUI "RefreshIndicator")))
(def select-field nil #_(r/adapt-react-class (aget js/MaterialUI "SelectField")))
(def slider nil #_(r/adapt-react-class (aget js/MaterialUI "Slider")))
(def subheader nil #_(r/adapt-react-class (aget js/MaterialUI "Subheader")))
(def svg-icon nil #_(r/adapt-react-class (aget js/MaterialUI "SvgIcon")))
(def step nil #_(r/adapt-react-class (aget js/MaterialUI "Step")))
(def step-button nil #_(r/adapt-react-class (aget js/MaterialUI "StepButton")))
(def step-content nil #_(r/adapt-react-class (aget js/MaterialUI "StepContent")))
(def step-label nil #_(r/adapt-react-class (aget js/MaterialUI "StepLabel")))
(def stepper nil #_(r/adapt-react-class (aget js/MaterialUI "Stepper")))
(def snackbar nil #_(r/adapt-react-class (aget js/MaterialUI "Snackbar")))
(def tabs nil #_(r/adapt-react-class (aget js/MaterialUI "Tabs")))
(def tab nil #_(r/adapt-react-class (aget js/MaterialUI "Tab")))
(def table nil #_(r/adapt-react-class (aget js/MaterialUI "Table")))
(def table-body nil #_(r/adapt-react-class (aget js/MaterialUI "TableBody")))
(def table-footer nil #_(r/adapt-react-class (aget js/MaterialUI "TableFooter")))
(def table-header nil #_(r/adapt-react-class (aget js/MaterialUI "TableHeader")))
(def table-header-column nil #_(r/adapt-react-class (aget js/MaterialUI "TableHeaderColumn")))
(def table-row nil #_(r/adapt-react-class (aget js/MaterialUI "TableRow")))
(def table-row-column nil #_(r/adapt-react-class (aget js/MaterialUI "TableRowColumn")))
(def text-field (r/adapt-react-class (aget js/MaterialUI "TextField")))
(def time-picker nil #_(r/adapt-react-class (aget js/MaterialUI "TimePicker")))
(def toggle nil #_(r/adapt-react-class (aget js/MaterialUI "Toggle")))
(def toolbar nil #_(r/adapt-react-class (aget js/MaterialUI "Toolbar")))
(def toolbar-group nil #_(r/adapt-react-class (aget js/MaterialUI "ToolbarGroup")))
(def toolbar-separator nil #_(r/adapt-react-class (aget js/MaterialUI "ToolbarSeparator")))
(def toolbar-title nil #_(r/adapt-react-class (aget js/MaterialUI "ToolbarTitle")))