(ns ote.mui-wrapper.rum
  (:refer-clojure :exclude [list stepper])
  (:require-macros [ote.mui-wrapper.core])
  (:require [rum.core]
            [ote.mui-wrapper.core]))

;TODO useless

(def selectable-list (ote.mui-wrapper.core/adapt-rum-class ((aget js/MaterialUI "makeSelectable") (aget js/MaterialUI "List"))))

(def app-bar (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "AppBar")))
(def auto-complete (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "AutoComplete")))
(def avatar (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Avatar")))
(def badge (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Badge")))
(def bottom-navigation (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "BottomNavigation")))
(def bottom-navigation-item (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "BottomNavigationItem")))
(def card (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Card")))
(def card-actions (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "CardActions")))
(def card-header (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "CardHeader")))
(def card-media (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "CardMedia")))
(def card-title (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "CardTitle")))
(def card-text (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "CardText")))
(def checkbox (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Checkbox")))
(def chip (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Chip")))
(def circular-progress (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "CircularProgress")))
(def date-picker (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "DatePicker")))
(def dialog (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Dialog")))
(def divider (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Divider")))
(def drawer (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Drawer")))
(def drop-down-menu (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "DropDownMenu")))
(def flat-button (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "FlatButton")))
(def floating-action-button (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "FloatingActionButton")))
(def font-icon (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "FontIcon")))
(def grid-list (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "GridList")))
(def grid-tile (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "GridTile")))
(def icon-button (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "IconButton")))
(def icon-menu (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "IconMenu")))
(def linear-progress (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "LinearProgress")))
(def list (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "List")))
(def list-item (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "ListItem")))
(def menu (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Menu")))
(def menu-item (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "MenuItem")))
(def mui-theme-provider (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "MuiThemeProvider")))
(def paper (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Paper")))
(def popover (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Popover")))
(def radio-button (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "RadioButton")))
(def radio-button-group (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "RadioButtonGroup")))
(def raised-button (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "RaisedButton")))
(def refresh-indicator (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "RefreshIndicator")))
(def select-field (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "SelectField")))
(def slider (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Slider")))
(def subheader (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Subheader")))
(def svg-icon (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "SvgIcon")))
(def step (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Step")))
(def step-button (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "StepButton")))
(def step-content (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "StepContent")))
(def step-label (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "StepLabel")))
(def stepper (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Stepper")))
(def snackbar (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Snackbar")))
(def tabs (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Tabs")))
(def tab (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Tab")))
(def table (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Table")))
(def table-body (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TableBody")))
(def table-footer (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TableFooter")))
(def table-header (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TableHeader")))
(def table-header-column (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TableHeaderColumn")))
(def table-row (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TableRow")))
(def table-row-column (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TableRowColumn")))
(def text-field (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TextField")))
(def time-picker (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "TimePicker")))
(def toggle (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Toggle")))
(def toolbar (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "Toolbar")))
(def toolbar-group (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "ToolbarGroup")))
(def toolbar-separator (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "ToolbarSeparator")))
(def toolbar-title (ote.mui-wrapper.core/adapt-rum-class (aget js/MaterialUI "ToolbarTitle")))