# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry

# If you want to rebuild each container using local dockerfiles, remove comments from the "build" lines.

version: "3"

networks:
  napote:

services:
  napote-ckan:
    container_name: napote-ckan
    build:
      context: ./ckan
      args:
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_PORT=${CKAN_PORT}
    #image: solita/napote-ckan:latest
    networks:
      - napote
    links:
      - napotedb
      - napote-solr
      - napote-redis
    ports:
      - "${CKAN_PORT}:5000"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:@napotedb:5432/ckan
      - CKAN_SOLR_URL=http://napote-solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://napote-redis:6379/1
      - CKAN_SITE_ID=${CKAN_SITE_ID}
      - CKAN_SITE_URL=${CKAN_SITE_URL}

  napotedb:
    restart: always
    container_name: napotedb
    build: ../../database/
    #image: solita/napotedb:latest
    networks:
      - napote
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

  napote-solr:
    container_name: napote-solr
    build: ./solr
    #image: solita/napote-solr:latest
    networks:
      - napote
    ports:
      - "8983:8983"

  napote-redis:
    container_name: napote-redis
    build: ./redis
    #image: solita/napote-redis:latest
    networks:
      - napote
    ports:
      - "6379:6379"

  napote-nginx:
    restart: always
    container_name: napote-nginx
    build: ./nginx
    #image: solita/napote-nginx:latest
    network_mode: "host"
