# docker-compose build && docker-compose up

# If you want to rebuild each container using local dockerfiles, remove comments from the "build" lines.

version: "3"

networks:
  napote:

services:
  napotedbpsql11:
    restart: always
    container_name: napotedb11
    image: solita/napotedb11:latest
    build: ../../database/
    networks:
      - napote
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

