# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry

# If you want to rebuild each container using local dockerfiles, remove comments from the "build" lines.

version: "3"

networks:
  napote:

services:
  napotedb:
    restart: always
    container_name: napotedb
    image: solita/napotedb:latest
    build: ../../database/
    networks:
      - napote
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
