- name: Create CKAN config and storage directory
  file: path={{item}} state=directory owner=napote group=napote
  with_items:
    - /etc/ckan/default
    - /var/lib/ckan/storage
  tags: configuration

- name: Write CKAN config from template
  template: src=../templates/ckan.ini.j2 dest=/etc/ckan/default/ckan.ini
  tags: configuration

- name: Copy who.ini
  shell: cp /usr/lib/ckan/default/src/ckan/ckan/config/who.ini /etc/ckan/default/
  tags: configuration

- name: Write startup script
  template: src=templates/ckan.sh.j2 dest=/usr/lib/ckan/default/ckan.sh mode=755
  tags: configuration

- name: Write service config
  template: src=templates/centos7-service-template.j2 dest=/etc/systemd/system/ckan.service mode=755
  with_items:
    - description: "CKAN"
      start_file: /usr/lib/ckan/default/ckan.sh
      user_name: napote
      user_group: napote
      workingdir: /usr/lib/ckan/default/
  tags: configuration

- name: Start CKAN service
  service: name=ckan state=restarted
  register: start

- name: Wait for CKAN to be up
  uri: url=http://localhost:5000/ status_code=200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  tags: configuration