- name: Install required packages
  yum: name={{item}} state=installed
  with_items:
    - gcc
    - postgresql-devel
    - python2-pip
    - python-devel
    - python-virtualenv
    - git-core

- name: Create CKAN directory
  file:
    path: /usr/lib/ckan/default
    state: directory
    owner: napote
    group: napote

- name: Initialize virtualenv
  command: virtualenv /usr/lib/ckan/default -p python2.7 creates="/usr/lib/ckan/default"

- name: Install setuptools
  pip:
    name: setuptools
    version: 36.5.0
    virtualenv: /usr/lib/ckan/default
    virtualenv_python: python2.7

- name: Upgrade PIP
  pip:
    version: 9.0.1
    name: pip
    virtualenv: /usr/lib/ckan/default
    virtualenv_python: python2.7

- name: Install CKAN stable sources
  pip:
    editable: true
    name: 'git+https://github.com/ckan/ckan.git@ckan-2.7.0#egg=ckan'
    virtualenv: /usr/lib/ckan/default
    virtualenv_python: python2.7


- name: Install pytz
  pip:
    editable: true
    version: 2016.7
    name: pytz
    virtualenv: /usr/lib/ckan/default
    virtualenv_python: python2.7

- name: Install CKAN dependencies
  pip:
    requirements: /usr/lib/ckan/default/src/ckan/requirements.txt
    virtualenv: /usr/lib/ckan/default
    virtualenv_python: python2.7
