- name: Create CKAN config directory
  file:
    path: /etc/ckan/default
    state: directory
    owner: napote
    group: napote

- name: Write CKAN config from template
  template: src=../templates/ckan.ini.j2 dest=/etc/ckan/default/ckan.ini
  tags: configuration

- name: Copy who.ini
  shell: cp /usr/lib/ckan/default/src/ckan/ckan/config/who.ini /etc/ckan/default/
  tags: configuration
