- name: Luo CKAN konfiguraatiohakemisto
  file:
    path: /etc/ckan/default
    state: directory
    owner: napote
    group: napote

- name: Kirjoita CKAN konfiguraatiotiedosto
  template: src=../templates/ckan.ini.j2 dest=/etc/ckan/default/ckan.ini