- name: Install required SOLR packages
  yum: name={{item}} state=installed
  with_items:
    - java-1.8.0-openjdk
    - git
    - curl
    - lsof
    - initscripts
    - wget

- name: Create SOLR distribution download directory
  file: path=/opt/solr-download state=directory owner=napote group=napote

- name: Download SOLR distribution
  get_url:
    url: http://archive.apache.org/dist/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz
    dest: /opt/solr-download/solr-{{solr_version}}.tgz

- name: Unpack SOLR distribution
  unarchive:
    remote_src: yes
    src: /opt/solr-download/solr-{{solr_version}}.tgz
    dest: /opt/solr-download

- name: Run SOLR installer
  shell: sh /opt/solr-download/solr-{{solr_version}}/bin/install_solr_service.sh /opt/solr-download/solr-{{solr_version}}.tgz -f
  args:
    creates: /opt/solr-{{solr_version}}

- name: Download CKAN distribution to get schema
  git:
    clone: yes
    repo: 'https://github.com/ckan/ckan.git'
    version: ckan-2.7.0
    dest: /opt/ckan-download

- name: Stop SOLR
  service: name=solr state=stopped

- name: Make directories
  file: path=/var/solr/data/ckan/{{item}} state=directory
  with_items:
    - conf
    - data

- name: Create solrconfig.ml from template
  template: src=templates/solrconfig.xml.j2 dest=/var/solr/data/ckan/conf/solrconfig.xml

- name: Copy other config files
  shell: cp /opt/solr-download/solr-{{solr_version}}/server/solr/configsets/{{item}} /var/solr/data/ckan/conf/
  with_items:
    - basic_configs/conf/currency.xml
    - basic_configs/conf/synonyms.txt
    - basic_configs/conf/stopwords.txt
    - basic_configs/conf/protwords.txt
    - data_driven_schema_configs/conf/elevate.xml

- name: Copy CKAN schema
  shell: cp /opt/ckan-download/ckan/config/solr/schema.xml /var/solr/data/ckan/conf/

- name: Create core.properties
  template: src=templates/core.properties.j2 dest=/var/solr/data/ckan/core.properties

- name: Give permissions to solr user
  shell: chown -R solr {{item}}
  with_items:
    - /opt/solr/
    - /var/solr

- name: Start SOLR
  service: name=solr state=restarted